# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f854a2c70a47771c61ea9f57409a0700826b73c85f57c9f6931c41ddcdeea47e7f8a835ec476a8190b6143f8839ac0f6b04b8ac62617f530b3933a10caa79deb

test:
  secret_key_base: 8004c40f573357cabaaa42bd254b824eb1ccc0ce1562f22871236d6b5e912798f8e26267099819a036eb72ae02471d15e149fff075beb1ca57b490017cb425fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
